# I. Exploratory Data Analysis

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import prince
import pprint
from datetime import date
import calendar
import warnings
warnings.filterwarnings("ignore") #ignore warnings

In [54]:
train = pd.read_csv('C:/Users/Will Jiang/Desktop/Emory Desktop/ML/Final Project/Project Data/Train000.csv')
test = pd.read_csv('C:/Users/Will Jiang/Desktop/Emory Desktop/ML/Final Project/Project Data/Train001.csv')

In [55]:
train.columns = ['id', 'click', 'hour', 'C1', 'banner_pos', 'site_id', 'site_domain',
       'site_category', 'app_id', 'app_domain', 'app_category', 'device_id',
       'device_ip', 'device_model', 'device_type', 'device_conn_type', 'C14',
       'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21']
test.columns = ['id', 'click', 'hour', 'C1', 'banner_pos', 'site_id', 'site_domain',
       'site_category', 'app_id', 'app_domain', 'app_category', 'device_id',
       'device_ip', 'device_model', 'device_type', 'device_conn_type', 'C14',
       'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21']

In [59]:
df = pd.concat([train, test], axis=0)

In [60]:
df

,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,10258522767243640572,0,14102819,1010,1,85f751fd,c4e18dd6,50e219e0,3fd3187a,7801e8d9,...,4,3,16252,320,50,1809,0,171,100162,126
1,7801328047195758573,0,14102516,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15706,320,50,1722,0,35,-1,79
2,16046150418661423859,0,14102410,1005,1,92c7cbe7,6e882918,75fa27f6,ecad2386,7801e8d9,...,1,0,16615,320,50,1863,3,39,-1,23
3,12577991248190121985,0,14102316,1005,0,85f751fd,c4e18dd6,50e219e0,7358e05e,b9528b13,...,1,0,1039,320,50,178,3,1327,100148,15
4,4502759030559738848,0,14102106,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15702,320,50,1722,0,35,100084,79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999994,10098856733302605049,0,14102515,1005,1,5b4d2eda,16a36ef3,f028772b,ecad2386,7801e8d9,...,1,0,19950,320,50,1800,3,167,100074,23
999995,10960190990062572433,0,14102423,1005,0,29229f8e,a10eb148,f028772b,ecad2386,7801e8d9,...,1,0,20392,320,50,2340,3,41,100111,159
999996,14398417496384268574,0,14102822,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,22916,320,50,2617,0,35,100083,51
999997,2581431362639724853,0,14102314,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15699,320,50,1722,0,35,100084,79
999998,8071147955329924932,0,14102302,1005,0,85f751fd,c4e18dd6,50e219e0,a5184c22,b8d325c3,...,1,2,14265,320,50,1526,2,169,100111,35

In [61]:
df.shape

(1999998, 24)

In [62]:
for i in df.columns:
    print(i,':')
    print('unique values:',len(df[i].unique()))
    print(df[i].value_counts())

id :
unique values: 1999998
10258522767243640572    1
4622489688683405260     1
9890169602338712078     1
7944358733327228718     1
16034083714956323691    1
                       ..
6018775237159500135     1
14417658251488341250    1
9094595560663684517     1
2483707199375430332     1
8071147955329924932     1
Name: id, Length: 1999998, dtype: int64
click :
unique values: 2
0    1659717
1     340281
Name: click, dtype: int64
hour :
unique values: 216
14102209    24731
14102210    24305
14102813    23868
14102212    22613
14102211    21448
            ...
14102419     1878
14102423     1407
14102420     1259
14102421     1164
14102422      787
Name: hour, Length: 216, dtype: int64
C1 :
unique values: 7
1005    1831635
1002     112777
1010      47178
1012       5773
1007       1827
1001        470
1008        338
Name: C1, dtype: int64
banner_pos :
unique values: 7
0    1429928
1     566292
7       2240
2        696
4        403
5        338
3        101
Name: banner_pos, dtype: int64
site_id :
unique values: 3012
85f751fd    697225
1fbe01fe    326551
e151e245    130619
d9750ee7     49168
5b08c53b     44794
             ...
8429c256         1
2cea1581         1
b035f744         1
c35b70ac         1
e421a0c5         1
Name: site_id, Length: 3012, dtype: int64
site_domain :
unique values: 3463
c4e18dd6    724050
f3845767    326551
7e091613    167749
7687a86e     63590
98572c79     50998
             ...
3c2866d3         1
c8ccbcfd         1
40a2e1b7         1
062e57c6         1
2e3797b1         1
Name: site_domain, Length: 3463, dtype: int64
site_category :
unique values: 21
50e219e0    795204
f028772b    638667
28905ebd    372269
3e814130    152631
f66779e6     13380
75fa27f6      8543
335d28a8      6702
76b2941d      5597
c0dd3be3      2146
72722551      1351
dedf689d      1260
0569f928       913
70fb0e29       792
a818d37a       155
42a36e14       136
8fd0aea4       114
e787de0e        63
bcf865d9        42
5378d028        21
9ccfa2ea        11
da34532e         1
Name: site_category, dtype: int64
app_id :
unique values: 3960
ecad2386    1302773
92f5800b      85566
e2fcccd2      55523
febd1138      37400
7358e05e      31878
             ...
774be746          1
9a63ed2f          1
a31274bd          1
854ececa          1
51afb05f          1
Name: app_id, Length: 3960, dtype: int64
app_domain :
unique values: 259
7801e8d9    1375608
2347f47a     231721
ae637522     102333
5c5a694b      55537
82e27996      37402
             ...
28a85b13          1
dcb74110          1
e559a22e          1
8ab0d4f4          1
e9d5949e          1
Name: app_domain, Length: 259, dtype: int64
app_category :
unique values: 29
07d7df22    1320391
0f2161f8     466932
cef3e649      88528
8ded1f7a      64064
f95efa07      41638
d1327cf5       6244
09481d60       2990
dc97ec06       2791
75d80bbe       2106
fc6fa53d       1195
4ce2e9fc        977
879c24eb        611
a3c42688        520
4681bb9d        304
0f9a328c        289
2281a340        110
a86a3e89        106
8df2e842         88
79f0b860         30
0bfbc358         26
a7fd01ec         15
2fc4f2aa         13
7113d72a         11
18b1e0be         10
5326cf99          4
bf8ac856          2
4b7ade46          1
0d82db25          1
71af18ce          1
Name: app_category, dtype: int64
device_id :
unique values: 280711
a99f214a    1645316
c357dbff       1107
936e92fb        678
0f7c61dc        602
afeffc18        489
             ...
6eea9734          1
19e31f74          1
70b7c13e          1
9b8aa70d          1
de3213f9          1
Name: device_id, Length: 280711, dtype: int64
device_ip :
unique values: 944568
6b9769f2    10557
431b3174     6787
2f323f36     4816
af9205f9     4741
930ec31d     4691
            ...
b0af9715        1
312e4ac7        1
bac4c9b1        1
a3b82e6b        1
fd4aa231        1
Name: device_ip, Length: 944568, dtype: int64
device_model :
unique values: 5782
8a4875bd    122195
1f0bc64f     69286
d787e91b     68426
76dc4769     37540
be6db1d7     35745
             ...
3f217a90         1
f2b645ce         1
0fc69d3d         1
6774324d         1
9da469b1         1
Name: device_model, Length: 5782, dtype: int64
device_type :
unique values: 5
1    1840042
0     112777
4      40575
5       6603
2          1
Name: device_type, dtype: int64
device_conn_type :
unique values: 4
0    1730837
2     155459
3     111447
5       2255
Name: device_conn_type, dtype: int64
C14 :
unique values: 2253
4687     50385
21611    45270
21189    42237
21191    42150
19771    37214
         ...
23485        1
16404        1
18552        1
23101        1
22486        1
Name: C14, Length: 2253, dtype: int64
C15 :
unique values: 8
320     1865426
300      114440
216       15986
728        3643
120         177
1024        132
480         110
768          84
Name: C15, dtype: int64
C16 :
unique values: 9
50      1885223
250       89206
36        15986
480        5437
90         3643
20          177
768         132
320         110
1024         84
Name: C16, dtype: int64
C17 :
unique values: 403
1722    240321
2424     84388
2227     74983
1800     63447
423      50385
         ...
2447         1
644          1
2575         1
2448         1
2585         1
Name: C17, Length: 403, dtype: int64
C18 :
unique values: 4
0    832200
3    673815
2    347231
1    146752
Name: C18, dtype: int64
C19 :
unique values: 65
35      624036
39      450382
167     159124
161      86527
47       55300
         ...
683         33
1195        11
1447         9
545          4
677          1
Name: C19, Length: 65, dtype: int64
C20 :
unique values: 166
-1         927600
 100084    123640
 100111     89313
 100148     87153
 100077     79059
            ...
 100078         2
 100157         1
 100209         1
 100027         1
 100006         1
Name: C20, Length: 166, dtype: int64
C21 :
unique values: 55
23     434782
79     243994
221    236549
71     115036
48     111888
157    102998
61     101296
32      90611
33      74012
52      59616
42      54335
15      41468
51      34608
212     33591
43      31796
117     23295
13      20459
156     18431
68      17908
16      16039
159     15884
95      12930
46      12576
69       9687
91       9191
111      7721
70       7125
90       6707
110      6662
204      5092
171      4831
17       4625
112      4121
101      4114
82       3607
100      3351
178      2837
182      2767
108      2600
35       2569
253      1605
251       975
116       852
194       738
20        732
93        700
94        698
126       434
102       381
163       369
177       326
195       225
1         167
219        68
85         19
Name: C21, dtype: int64

In [63]:
for i in df.columns:
    print(i,len(df[i].unique()))

id 1999998
click 2
hour 216
C1 7
banner_pos 7
site_id 3012
site_domain 3463
site_category 21
app_id 3960
app_domain 259
app_category 29
device_id 280711
device_ip 944568
device_model 5782
device_type 5
device_conn_type 4
C14 2253
C15 8
C16 9
C17 403
C18 4
C19 65
C20 166
C21 55

# II. Feature Engineering

## Generate weekday and time period by hour

In [64]:
# check the time range
print(np.max(df.hour))
print(np.min(df.hour))

14102923
14102100

In [65]:
# define a function to get the weekday of the time
def get_date(hour):
    y = '20'+str(hour)[:2]
    m = str(hour)[2:4]
    d = str(hour)[4:6]
    return y + '-' + m + '-' + d

In [66]:
# get the weekday
df['weekday'] = pd.to_datetime(df.hour.apply(get_date)).dt.day_name()
df['weekday']

0          Tuesday
1         Saturday
2           Friday
3         Thursday
4          Tuesday
            ...
999994    Saturday
999995      Friday
999996     Tuesday
999997    Thursday
999998    Thursday
Name: weekday, Length: 1999998, dtype: object

In [67]:
# define a function to get the hour of the time
def get_hour(hour):
    h = str(hour)[6:8]
    h = int(h)
    return h

In [68]:
# get the hour
df['hour'] = df.hour.apply(get_hour)
df['hour']

0         19
1         16
2         10
3         16
4          6
          ..
999994    15
999995    23
999996    22
999997    14
999998     2
Name: hour, Length: 1999998, dtype: int64

In [69]:
# transfer to time period
df.loc[df.hour.between(6,12), 'time_period'] = 'morning'
df.loc[df.hour.between(13,18), 'time_period'] = 'afternoon'
df.loc[df.hour.between(19,24), 'time_period'] = 'night'
df.loc[df.hour.between(0,5), 'time_period'] = 'mid_night'

In [70]:
# drop columns won't be used for modeling
df = df.drop(['id','hour'], axis=1)

## Transfer categories with only one unique values to others

In [71]:
good_col = ['click','C1','banner_pos','device_type','device_conn_type','C15','C16','C18','weekday','time_period']

In [72]:
for i in [x for x in df.columns if x not in good_col]:
    cnt = df[i].value_counts()
    row = cnt[cnt == 1].index.tolist()
    df.loc[df[i].isin(row),i] = 'others'

In [73]:
# check if successful
df[df.site_id == 'others']

,click,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,app_category,device_id,...,C14,C15,C16,C17,C18,C19,C20,C21,weekday,time_period
1660,0,1005,0,others,2ec930cc,f028772b,ecad2386,7801e8d9,07d7df22,a99f214a,...,20018,300,250,2286,3,39,-1,23,Thursday,mid_night
3368,0,1005,0,others,others,28905ebd,ecad2386,7801e8d9,07d7df22,a99f214a,...,17863,300,250,2036,3,47,-1,156,Sunday,morning
5899,0,1005,0,others,291d278b,3e814130,ecad2386,7801e8d9,07d7df22,a99f214a,...,13644,320,50,1447,2,47,100075,13,Saturday,afternoon
9209,0,1005,0,others,5449fde7,f028772b,ecad2386,7801e8d9,07d7df22,a99f214a,...,16920,320,50,1899,0,431,100081,117,Thursday,morning
11758,1,1005,0,others,2ec930cc,f028772b,ecad2386,7801e8d9,07d7df22,a99f214a,...,17863,300,250,2036,3,47,-1,156,Wednesday,morning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973848,0,1002,0,others,1e0acfb4,50e219e0,ecad2386,7801e8d9,07d7df22,others,...,15908,320,50,1752,3,297,100081,82,Sunday,morning
974120,0,1005,0,others,others,f028772b,ecad2386,7801e8d9,07d7df22,a99f214a,...,19950,320,50,1800,3,167,100075,23,Sunday,afternoon
979170,0,1002,0,others,ec266924,50e219e0,ecad2386,7801e8d9,07d7df22,others,...,6563,320,50,572,2,39,-1,32,Sunday,mid_night
989443,1,1005,0,others,others,f028772b,ecad2386,7801e8d9,07d7df22,a99f214a,...,18454,320,50,2104,0,559,-1,171,Sunday,afternoon
989833,0,1002,0,others,others,50e219e0,ecad2386,7801e8d9,07d7df22,others,...,15908,320,50,1752,3,297,100081,82,Wednesday,mid_night

## MFA (Not used)

In [28]:
df_sub = df.loc[:,['C21','C20']]

In [49]:
df_sub = pd.get_dummies(df_sub,drop_first = True)
df_sub

,C21_13,C21_15,C21_16,C21_17,C21_20,C21_23,C21_32,C21_33,C21_35,C21_42,...,C20_100217,C20_100221,C20_100224,C20_100225,C20_100228,C20_100229,C20_100233,C20_100241,C20_100244,C20_100248
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999996,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [54]:
groups = {
    'C{}'.format(no): [c for c in df_sub.columns if c.startswith('C{}'.format(no))]
    for no in [20,21]
}

In [55]:
pprint.pprint(groups)

{'C20': ['C20_100000',
         'C20_100001',
         'C20_100002',
         'C20_100003',
         'C20_100004',
         'C20_100005',
         'C20_100010',
         'C20_100012',
         'C20_100013',
         'C20_100016',
         'C20_100019',
         'C20_100020',
         'C20_100021',
         'C20_100022',
         'C20_100024',
         'C20_100025',
         'C20_100026',
         'C20_100028',
         'C20_100029',
         'C20_100031',
         'C20_100032',
         'C20_100033',
         'C20_100034',
         'C20_100037',
         'C20_100039',
         'C20_100040',
         'C20_100041',
         'C20_100043',
         'C20_100046',
         'C20_100048',
         'C20_100049',
         'C20_100050',
         'C20_100051',
         'C20_100052',
         'C20_100053',
         'C20_100054',
         'C20_100055',
         'C20_100056',
         'C20_100057',
         'C20_100058',
         'C20_100059',
         'C20_100060',
         'C20_100061',
         'C20_100062',
         'C20_100063',
         'C20_100064',
         'C20_100065',
         'C20_100068',
         'C20_100070',
         'C20_100071',
         'C20_100072',
         'C20_100073',
         'C20_100074',
         'C20_100075',
         'C20_100076',
         'C20_100077',
         'C20_100078',
         'C20_100079',
         'C20_100081',
         'C20_100082',
         'C20_100083',
         'C20_100084',
         'C20_100086',
         'C20_100087',
         'C20_100088',
         'C20_100090',
         'C20_100091',
         'C20_100093',
         'C20_100094',
         'C20_100095',
         'C20_100096',
         'C20_100097',
         'C20_100098',
         'C20_100099',
         'C20_100100',
         'C20_100101',
         'C20_100103',
         'C20_100105',
         'C20_100106',
         'C20_100107',
         'C20_100108',
         'C20_100109',
         'C20_100111',
         'C20_100112',
         'C20_100113',
         'C20_100114',
         'C20_100117',
         'C20_100119',
         'C20_100121',
         'C20_100122',
         'C20_100123',
         'C20_100124',
         'C20_100126',
         'C20_100128',
         'C20_100130',
         'C20_100131',
         'C20_100133',
         'C20_100135',
         'C20_100137',
         'C20_100138',
         'C20_100139',
         'C20_100141',
         'C20_100143',
         'C20_100144',
         'C20_100148',
         'C20_100149',
         'C20_100150',
         'C20_100151',
         'C20_100152',
         'C20_100153',
         'C20_100155',
         'C20_100156',
         'C20_100160',
         'C20_100161',
         'C20_100162',
         'C20_100163',
         'C20_100165',
         'C20_100166',
         'C20_100168',
         'C20_100169',
         'C20_100170',
         'C20_100171',
         'C20_100172',
         'C20_100173',
         'C20_100175',
         'C20_100176',
         'C20_100177',
         'C20_100178',
         'C20_100179',
         'C20_100181',
         'C20_100182',
         'C20_100183',
         'C20_100185',
         'C20_100186',
         'C20_100188',
         'C20_100189',
         'C20_100190',
         'C20_100191',
         'C20_100192',
         'C20_100193',
         'C20_100194',
         'C20_100195',
         'C20_100199',
         'C20_100200',
         'C20_100202',
         'C20_100205',
         'C20_100206',
         'C20_100210',
         'C20_100212',
         'C20_100213',
         'C20_100215',
         'C20_100217',
         'C20_100221',
         'C20_100224',
         'C20_100225',
         'C20_100228',
         'C20_100229',
         'C20_100233',
         'C20_100241',
         'C20_100244',
         'C20_100248'],
 'C21': ['C21_13',
         'C21_15',
         'C21_16',
         'C21_17',
         'C21_20',
         'C21_23',
         'C21_32',
         'C21_33',
         'C21_35',
         'C21_42',
         'C21_43',
         'C21_46',
         'C21_48',
         'C21_51',
         'C21_52',
         'C21_61',
         'C21_68',
         'C21_69',
         'C21_70',
         'C21_71',
         'C21_79',
         'C21_82',
         'C21_85',
         'C21_90',
         'C21_91',
         'C21_93',
         'C21_94',
         'C21_95',
         'C21_100',
         'C21_101',
         'C21_102',
         'C21_108',
         'C21_110',
         'C21_111',
         'C21_112',
         'C21_116',
         'C21_117',
         'C21_126',
         'C21_156',
         'C21_157',
         'C21_159',
         'C21_163',
         'C21_171',
         'C21_177',
         'C21_178',
         'C21_182',
         'C21_194',
         'C21_195',
         'C21_204',
         'C21_212',
         'C21_219',
         'C21_221',
         'C21_251',
         'C21_253']}

In [56]:
mfa = prince.MFA(groups=groups,n_components=5,random_state=42)

In [64]:
mfa = prince.MFA(
groups=groups,
n_components=2,
n_iter=3,
copy=True,
check_input=True,
engine='auto',
random_state=42
)

In [65]:
mfa_out = mfa.fit(df_sub)

In [67]:
print(mfa_out)

MFA(groups={'C20': ['C20_100000', 'C20_100001', 'C20_100002', 'C20_100003',
                    'C20_100004', 'C20_100005', 'C20_100010', 'C20_100012',
                    'C20_100013', 'C20_100016', 'C20_100019', 'C20_100020',
                    'C20_100021', 'C20_100022', 'C20_100024', 'C20_100025',
                    'C20_100026', 'C20_100028', 'C20_100029', 'C20_100031',
                    'C20_100032', 'C20_100033', 'C20_100034', 'C20_100037',
                    'C20_100039', 'C20_1..._100043',
                    'C20_100046', 'C20_100048', ...],
            'C21': ['C21_13', 'C21_15', 'C21_16', 'C21_17', 'C21_20', 'C21_23',
                    'C21_32', 'C21_33', 'C21_35', 'C21_42', 'C21_43', 'C21_46',
                    'C21_48', 'C21_51', 'C21_52', 'C21_61', 'C21_68', 'C21_69',
                    'C21_70', 'C21_71', 'C21_79', 'C21_82', 'C21_85', 'C21_90',
                    'C21_91', 'C21_93', 'C21_94', 'C21_95', 'C21_100',
                    'C21_101', ...]},
    n_iter=3, random_state=42)

In [68]:
mfa.explained_inertia_

array([0.00846218, 0.00792557])